### ISSUE TITLE
Exception while running "LxCommunicator.NET.Example.Websocket"

### ISSUE THREAD

**Issue by CalDymos** [Loxone/LxCommunicator.NET#3] opened 2020-05-27 10:58 UTC
while executing the example LxCommunicator.NET.Example.Websocket I always get an exception error (see picture)

![Exception](https://user-images.githubusercontent.com/65937830/83011133-ade03500-a019-11ea-9a1b-098f235e633c.png)

**Comment by CalDymos** [comment] 2020-05-28 04:51
I helped myself with a simple workaround, so at least status messages are still received.


`

if (!HandleWebserviceResponse(response) && !ParseEventTable(response.Content, response.Header.Type))

					{

						// TODO: Find out why the EventHandler "OnReceiveMssge" is sometimes empty.

						if (OnReceiveMessge != null) 

						{

						OnReceiveMessge.BeginInvoke(WebSocket, new MessageReceivedEventArgs(response), null, null);

						}

						//-----------------------------

					}
`

I think this will not solve the real problem, which is why "OnReceiveMessge" is sometimes empty.
I mainly program with VB.net and have little experience with C#.

**Comment by SvenVandenbrande** [comment] 2020-07-26 19:54
As I can see it has something to do with the "Loxone.Communicator.MessageType.EventTableWeatherStates".
The message is at that State empty, need to investigate further on that. This is with the "test miniserver"

Maybe @LxWolfgang knows what the issue is...

**Comment by loxone-mahriwo** [comment] 2020-07-27 06:25
@SvenVandenbrande The OnReceiveMessage is called when an unexpected message was received. I didn't had a detailed look on which messages are received, but neither HandleWebserverviceResponse nor ParseEventTable can consume the received message. Unfortunate the OnReceiveMessage Event is marked as private and there isn't any component that registers to it therefore it always is null. As pointed out by CalDymos the exception can be avoided by adding a null check.

`OnReceiveMessge?.BeginInvoke(WebSocket, new MessageReceivedEventArgs(response), null, null);`  

The next time we are going to make changes to the LxCommunicator.Net, we will take care of this issue.

**Comment by SvenVandenbrande** [comment] 2020-07-27 06:37
@LxWolfgang Do you accept a pull request for that? I can change it.
Would also be great to have that released via the nuget feed.

I would like to use the nuget package in a solution I am developing. :)

**Comment by loxone-mahriwo** [comment] 2020-08-03 12:03
With the pull request of @SvenVandenbrande the exception shouldn't be thrown anymore.
The source of the problem is likely an unhandled message type. For example the KeepAlive Response isn't handled at the moment and could caused the problem.

**Closed as completed by loxone-mahriwo** 2020-08-03 12:04 UTC
